### ISSUE TITLE
Strictly increasing

### ISSUE THREAD

**Issue by Meet090201vora** [Tanmay-901/test-case-generator#21]
# New test case type
### Test Case format (or example test case)
for ex - 
```
T
n
A1 A2 A3... An
```
`(In the format of CP websites or the ones shown in the generator application)`  
1st line -  
2nd line -  
3rd line -  
4th line -  
  
### Reference link to the question(URL):-  
`(It'll help us in analyzing the Test case better)`

### Email:-  
`(please provide your primary email id so that we can contact you for more details if required and we can inform you when the test case is successfully added).`

**Comment by Tanmay-901** [comment]
Hi @Meet090201vora, cannot see your suggestion in the issue. can you share the test case again? or if this was created by mistake then close the issue.

**Comment by Meet090201vora** [comment]
I will send the code.
