### ISSUE TITLE
TSuggest Test Case

### ISSUE THREAD

**Issue by MihirKotecha** [Tanmay-901/test-case-generator#23]
# New test case type
### Test Case format (or example test case)
for ex - 
```
T
n
A1 A2 A3... An
```
`(In the format of CP websites or the ones shown in the generator application)`  
1st line -  
2nd line -  
3rd line -  
4th line -  
  
### Reference link to the question(URL):-  
`(It'll help us in analyzing the Test case better)`

### Email:-  
`(please provide your primary email id so that we can contact you for more details if required and we can inform you when the test case is successfully added).`

**Comment by Tanmay-901** [comment]
Hi @MihirKotecha, Thanks for suggesting the test case. However, could you please check if the 3rd test case type in the generator is similar to the one you suggested?
If not, can you explain a bit about what exactly is the difference?

**Comment by MihirKotecha** [comment]
![image](https://user-images.githubusercontent.com/97303898/193753807-c7ede058-9bb3-4dc4-9b05-e44e7ad60a99.png)
I need space separated integers for each test case and not as pairs.

**Comment by Tanmay-901** [comment]
Still not able to get your point, the 3rd format gives space-separated integers, like the example below,
```
4
3 9
8 12
2 5
7 3
```
Is this acceptable?

**Comment by MihirKotecha** [comment]
Yes it is acceptable. The third category is the same. Really sorry for the inconvinience.

**Comment by Tanmay-901** [comment]
Sure np, thanks for trying to add value to the tool.
