### ISSUE TITLE
T 

### ISSUE THREAD

**Issue by AdityaMittal31** [Tanmay-901/test-case-generator#29]
# New test case type
### Test Case format (or example test case)
for ex - 
```
T
n
A1 A2 A3... An
```
`(In the format of CP websites or the ones shown in the generator application)`  
1st line -  
2nd line -  
3rd line -  
4th line -  
  
### Reference link to the question(URL):-  
`(It'll help us in analyzing the Test case better)`

**Comment by Tanmay-901** [comment]
Hi @AdityaMittal31 can't see the test case you might've wanted to add, kindly edit or resubmit the issue with proper details.

**Comment by Tanmay-901** [comment]
Closing this issue as not enough details were provided.
