### ISSUE TITLE
t

### ISSUE THREAD

**Issue by aditya955569** [Tanmay-901/test-case-generator#32]
# New test case type
### Test Case format (or example test case)
for ex - 
```
T
n
A1 A2 A3... An
```
`(In the format of CP websites or the ones shown in the generator application)`  
1st line -  
2nd line -  
3rd line -  
4th line -  
  
### Reference link to the question(URL):-  
`(It'll help us in analyzing the Test case better)`

**Comment by Tanmay-901** [comment]
No details mentioned.
