### ISSUE TITLE
Non uniformity in test cases values

### ISSUE THREAD

**Issue by sourabhkv** [Tanmay-901/test-case-generator#46]
i would like to have 20 numbers in range of 1 - 1 M but every time the generated numbers max lies around 10k it never passes 100k also could improve the randomness

**Comment by Tanmay-901** [comment]
Please note that the size of the maximum values in test cases already has an open [issue](https://github.com/Tanmay-901/test-case-generator/issues/3). 
The tool already uses the best random generators that are available to use openly, if you could provide specific details as to how the randomness can be improved that'd help in catering to the requirement better.

**Comment by Tanmay-901** [comment]
thread no longer active.
